### ISSUE TITLE
Clarify in README Differences vs pynetdicom3

### ISSUE THREAD

**Issue by cancan101** [patmun/pynetdicom23#4]
`pynetdicom3` claims python2.7 support so the difference of this library vs pynetdicom3 (from which it was formed) are unclear.

**Comment by patmun** [comment]
Yes, I agree. pynetdicom3 was python 3 only at the beginning and this library was my first attempt to backport it to python 2. Now that pynetdicom3 supports python 2 there is no need for pynetdicom23. I modified the readme,

**Comment by cancan101** [comment]
thanks!
